import { Order, Customer, LogisticsTracking, Shipment, User } from './types'

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'admin@euconx.com',
    name: 'Admin User',
    role: 'admin',
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: '2',
    email: 'manager@euconx.com',
    name: 'Operations Manager',
    role: 'manager',
    createdAt: '2025-01-01T00:00:00Z',
  },
]

export const mockCustomers: Customer[] = [
  {
    id: '1',
    name: 'Budapest Construction Ltd',
    email: 'orders@budapestconstruction.hu',
    phone: '+36 1 234 5678',
    company: 'Budapest Construction Ltd',
    address: 'Váci út 123',
    city: 'Budapest',
    country: 'Hungary',
    taxId: 'HU12345678',
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: '2',
    name: 'Debrecen Builders',
    email: 'procurement@debrecenbuilders.hu',
    phone: '+36 52 123 456',
    company: 'Debrecen Builders Kft',
    address: 'Piac utca 45',
    city: 'Debrecen',
    country: 'Hungary',
    taxId: 'HU87654321',
    createdAt: '2024-02-20T00:00:00Z',
  },
  {
    id: '3',
    name: 'Szeged Construction Group',
    email: 'info@szegedconstruction.hu',
    phone: '+36 62 987 654',
    company: 'Szeged Construction Group',
    address: 'Tisza Lajos krt 88',
    city: 'Szeged',
    country: 'Hungary',
    taxId: 'HU11223344',
    createdAt: '2024-03-10T00:00:00Z',
  },
]

export const mockOrders: Order[] = [
  {
    id: '1',
    orderNumber: 'ORD-2025-001',
    customerId: '1',
    customerName: 'Budapest Construction Ltd',
    customerEmail: 'orders@budapestconstruction.hu',
    status: 'in_transit',
    items: [
      {
        id: '1',
        productName: 'ODE Starflex Glass Wool Rolls',
        productCode: 'ODE-SF-150-R',
        quantity: 500,
        unit: 'm²',
        unitPrice: 12.5,
        totalPrice: 6250,
        manufacturer: 'ODE Insulation',
        specifications: '150mm thickness, λ=0.035 W/mK',
      },
      {
        id: '2',
        productName: 'BONUS XPS Thermal Boards',
        productCode: 'BON-XPS-100',
        quantity: 300,
        unit: 'm²',
        unitPrice: 18.0,
        totalPrice: 5400,
        manufacturer: 'BONUS Yalitim',
        specifications: '100mm thickness, λ=0.028 W/mK',
      },
    ],
    totalValue: 11650,
    currency: 'EUR',
    orderDate: '2025-09-28T10:30:00Z',
    estimatedDeliveryDate: '2025-10-12T00:00:00Z',
    notes: 'Urgent delivery required for project deadline',
    createdBy: '1',
    createdAt: '2025-09-28T10:30:00Z',
    updatedAt: '2025-10-03T14:20:00Z',
  },
  {
    id: '2',
    orderNumber: 'ORD-2025-002',
    customerId: '2',
    customerName: 'Debrecen Builders',
    customerEmail: 'procurement@debrecenbuilders.hu',
    status: 'ready_to_ship',
    items: [
      {
        id: '3',
        productName: 'IZOCAM Stone Wool Insulation',
        productCode: 'IZO-SW-200',
        quantity: 800,
        unit: 'm²',
        unitPrice: 15.5,
        totalPrice: 12400,
        manufacturer: 'IZOCAM Insulation',
        specifications: '200mm thickness, Fire rating A1',
      },
    ],
    totalValue: 12400,
    currency: 'EUR',
    orderDate: '2025-10-01T09:15:00Z',
    estimatedDeliveryDate: '2025-10-14T00:00:00Z',
    notes: 'Customer requested CE certificates with shipment',
    createdBy: '2',
    createdAt: '2025-10-01T09:15:00Z',
    updatedAt: '2025-10-04T11:00:00Z',
  },
  {
    id: '3',
    orderNumber: 'ORD-2025-003',
    customerId: '3',
    customerName: 'Szeged Construction Group',
    customerEmail: 'info@szegedconstruction.hu',
    status: 'in_production',
    items: [
      {
        id: '4',
        productName: 'ADO PVC Window Systems',
        productCode: 'ADO-PVC-70',
        quantity: 150,
        unit: 'units',
        unitPrice: 245.0,
        totalPrice: 36750,
        manufacturer: 'ADO Group',
        specifications: '70mm profile, triple glazing, U-value 0.8',
      },
      {
        id: '5',
        productName: 'ADOFLOOR LVT Flooring',
        productCode: 'ADO-LVT-6MM',
        quantity: 2000,
        unit: 'm²',
        unitPrice: 22.0,
        totalPrice: 44000,
        manufacturer: 'ADO Group',
        specifications: '6mm thickness, AC4 wear rating',
      },
    ],
    totalValue: 80750,
    currency: 'EUR',
    orderDate: '2025-10-03T13:45:00Z',
    estimatedDeliveryDate: '2025-10-20T00:00:00Z',
    notes: 'Large order for residential complex renovation',
    createdBy: '1',
    createdAt: '2025-10-03T13:45:00Z',
    updatedAt: '2025-10-05T09:30:00Z',
  },
  {
    id: '4',
    orderNumber: 'ORD-2025-004',
    customerId: '1',
    customerName: 'Budapest Construction Ltd',
    customerEmail: 'orders@budapestconstruction.hu',
    status: 'delivered',
    items: [
      {
        id: '6',
        productName: 'ODE R-Flex Rubber Foam',
        productCode: 'ODE-RF-19MM',
        quantity: 200,
        unit: 'm',
        unitPrice: 8.5,
        totalPrice: 1700,
        manufacturer: 'ODE Insulation',
        specifications: '19mm thickness, self-adhesive',
      },
    ],
    totalValue: 1700,
    currency: 'EUR',
    orderDate: '2025-09-15T08:00:00Z',
    estimatedDeliveryDate: '2025-09-28T00:00:00Z',
    actualDeliveryDate: '2025-09-27T14:30:00Z',
    notes: 'Express delivery completed',
    createdBy: '2',
    createdAt: '2025-09-15T08:00:00Z',
    updatedAt: '2025-09-27T14:30:00Z',
  },
]

export const mockLogistics: LogisticsTracking[] = [
  {
    id: '1',
    orderId: '1',
    status: 'confirmed',
    location: 'Istanbul, Turkey',
    timestamp: '2025-09-28T12:00:00Z',
    description: 'Order confirmed by manufacturer',
    updatedBy: '1',
  },
  {
    id: '2',
    orderId: '1',
    status: 'in_production',
    location: 'Antalya Production Facility, Turkey',
    timestamp: '2025-09-30T09:00:00Z',
    description: 'Production started',
    updatedBy: '1',
  },
  {
    id: '3',
    orderId: '1',
    status: 'ready_to_ship',
    location: 'Antalya Warehouse, Turkey',
    timestamp: '2025-10-02T16:00:00Z',
    description: 'Items packaged and ready for shipment',
    updatedBy: '1',
  },
  {
    id: '4',
    orderId: '1',
    status: 'in_transit',
    location: 'Border Crossing - Bulgaria/Hungary',
    timestamp: '2025-10-05T08:30:00Z',
    description: 'Cleared customs, in transit to Budapest',
    coordinates: { lat: 46.1833, lng: 20.7333 },
    updatedBy: '2',
  },
]

export const mockShipments: Shipment[] = [
  {
    id: '1',
    orderId: '1',
    trackingNumber: 'SHIP-2025-001-TR-HU',
    carrier: 'International Logistics GmbH',
    departureLocation: 'Antalya, Turkey',
    arrivalLocation: 'Budapest, Hungary',
    departureDate: '2025-10-03T06:00:00Z',
    estimatedArrivalDate: '2025-10-12T18:00:00Z',
    currentLocation: 'Belgrade, Serbia',
    status: 'In Transit',
    containerNumber: 'CONT-2025-TR-001',
    vehicleNumber: 'HU-ABC-123',
    driverName: 'János Kovács',
    driverPhone: '+36 20 123 4567',
  },
  {
    id: '2',
    orderId: '2',
    trackingNumber: 'SHIP-2025-002-TR-HU',
    carrier: 'EuroTrans Logistics',
    departureLocation: 'Istanbul, Turkey',
    arrivalLocation: 'Debrecen, Hungary',
    departureDate: '2025-10-06T08:00:00Z',
    estimatedArrivalDate: '2025-10-14T12:00:00Z',
    currentLocation: 'Istanbul Warehouse',
    status: 'Loading',
    containerNumber: 'CONT-2025-TR-002',
    vehicleNumber: 'HU-XYZ-789',
    driverName: 'Péter Nagy',
    driverPhone: '+36 30 987 6543',
  },
]
